### PR TITLE
Add travis to verify builds

### PR DESCRIPTION
**Pull request by siddharthkp**
This is the test matrix

```yml
os:
   - linux
   - osx
 node_js:
   - "7"
   - "6"
   - "5"
   - "4"
```

Check the results here - https://travis-ci.org/siddharthkp/react-workshop/builds/181562487

### CODE REVIEW

**Comment by siddharthkp** [comment]
@kentcdodds Should add Node version in the `README`. This only works on 6+

**Comment by kentcdodds** [comment]
Cool! Thanks! A few things. I only really care about node 6. I don't care to specify an OS. And I definitely want to keep the `yarn.lock` file as it is

**Comment by siddharthkp** [comment]
@kentcdodds For the workshop, you would want this to work on all OS, right?

**Comment by kentcdodds** [comment]
> For the workshop, you would want this to work on all OS, right?

Yes, but I expect that if it works on the default os (I think that's linux) it'll work on Mac. But that's fine. Too bad Travis doesn't support windows :-( That's normally the trouble.

Thanks for this. It's great!

**Comment by kentcdodds** [comment]
Thanks again for the PR!

<a href="https://github.com/kentcdodds/react-workshop#contributors">screen shot 2016-12-06 at 7 29 10 am</a>

**Comment by siddharthkp** [comment]
Your welcome :smile:

**Pull request merged**
